### ISSUE TITLE
Altair 5 issues

### ISSUE THREAD

**Issue by djhoese** [UW-Madison-DataScience/dataviz-workshop-example#1]
Altair came out with version 5.0 in early May. This is incompatible with the current stable version of streamlit. There is an issue for streamlit (https://github.com/streamlit/streamlit/issues/6215) and a PR that fixed it (https://github.com/streamlit/streamlit/pull/6618), but it hasn't been released yet. It *should* be released with streamlist 1.22.1 based on the latest tag shown at the bottom of the PR.

**Comment by djhoese** [comment]
Current workaround is to do this before running streamlit:

```bash
pip install "altair<5"
```

**Comment by djhoese** [comment]
Apparently streamlit 1.23 is out and supports altair 5, but the one installed on the gitpod is 1.11.1:

```
gitpod /workspace/dataviz-workshop-example (main) $ pip list | grep "streamlit"
streamlit   1.11.1
```

**Comment by sstevens2** [comment]
Thanks @djhoese!  Tested it out by letting it use the latest version of streamlit and seems to build correctly.  Think I'll leave it as such for now.  Though there was a time once where it had an issue because of a bug in the latest version of streamlit....so might not be the most trustworthy either.

**Comment by djhoese** [comment]
Are you going to force the version of altair then? Or always run the manual installation? Also note that the caching functionality available in streamlit changed a lot between the version used in your environment and the latest release. I played around with it last night and noticed the documentation didn't match.
